### ISSUE TITLE
Exception thrown by power-automate/desktop-flows  AddItemToList actions

### ISSUE THREAD

**Issue by wkirschenmann** [MicrosoftDocs/power-automate-docs#547]
The action produces an exception in the debugger : 

Message = Sequence contains more than one matching element
Error = System.InvalidOperationException
Full text = System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at WinAutomation.Designer.UI.FunctionsArea.ViewModels.FunctionViewModel.OnDebuggerExecutionChanged(Guid programItemId)
   at WinAutomation.Designer.UI.FunctionsArea.ViewModels.FunctionsAreaViewModel.<OnDebuggerExecutionChanged>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

I am only trying to add a string in a list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52e0d3b7-5d54-b28b-ed97-8bc0970d0c96
* Version Independent ID: c25847a1-f575-cfd9-73e5-10cdf75bbfa6
* Content: [Variables - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/variables#additemtolist)
* Content Source: [articles/desktop-flows/actions-reference/variables.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/variables.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by mariosleon** [comment]
Hello @wkirschenmann,  thank you for using Power Automate Desktop. This appears to be a technical issue. You may ask technical questions in the [Power Automate community](https://preview.flow.microsoft.com/en-us/support/) where technical experts can respond to questions and suggest solutions.

**Comment by wkirschenmann** [comment]
Hi,

I'd say that this is a bug in the HMI : my workflow works correctly but the "debugger" does not.
I do not really need a solution (my workflow works) but this is a bug that someone might want to correct. Who ? I do not know...
KR,
Wilfried
